alfg/mp4-rust

src/lib.rs
If the box size is non-zero, skip over it and continue reading. Otherwise if
the box size is zero, exit the loop.
=> Skip over unknown boxes

src/atoms.rs, src/lib.rs
- Add `boxtype` macro that can easily add new box type.
- Add `read_box_header_ext` macro that adds codes reading version and flags
- Fix parsing error when box has largesize
=> Remove deprecated codes

README.md, src/reader.rs
`ftyp` and `moov` should be public in the Mp4Reader for access, like the other boxes.
=> Mp4Reader and update README example

examples/mp4info.rs, src/mp4box/mp4a.rs, src/track.rs
* Also update `mp4info` example.
=> Set optional EsdsBox in Mp4aBox.

examples/mp4dump.rs, examples/simple.rs, src/lib.rs, src/mp4box/avc1.rs, src/mp4box/co64.rs, src/mp4box/ctts.rs, src/mp4box/edts.rs, src/mp4box/elst.rs, src/mp4box/ftyp.rs, src/mp4box/hdlr.rs, src/mp4box/mdhd.rs, src/mp4box/mdia.rs, src/mp4box/minf.rs, src/mp4box/mod.rs, src/mp4box/moov.rs, src/mp4box/mp4a.rs, src/mp4box/mvhd.rs, src/mp4box/smhd.rs, src/mp4box/stbl.rs, src/mp4box/stco.rs, src/mp4box/stsc.rs, src/mp4box/stsd.rs, src/mp4box/stss.rs, src/mp4box/stsz.rs, src/mp4box/stts.rs, src/mp4box/tkhd.rs, src/mp4box/trak.rs, src/mp4box/vmhd.rs
* Add `mp4dump` example, which can be improved once we have box paths implemented.
* `get_type` and `get_size` methods to all mp4box implementations
* Add `mp4::read_mp4` top level public function, which is basically a wrapper over the Mp4Reader.
=> Mp4dump example

src/writer.rs
This is useful in case an `Mp4Writer` is stored somewhere, owning its interior buffer and the buffer needs to be accessed after completion.
=> Add Mp4Writer::into_writer

src/mp4box/ftyp.rs, src/mp4box/hdlr.rs, src/mp4box/mod.rs, src/types.rs
String to FourCC now must go through `str::parse` and is fallible in case the string contains less than four bytes.
=> Store 4 bytes in FourCC instead of a String

src/mp4box/dinf.rs, src/mp4box/elst.rs, src/mp4box/hdlr.rs, src/mp4box/mdhd.rs, src/mp4box/mehd.rs, src/mp4box/mvhd.rs, src/mp4box/stsz.rs, src/mp4box/tkhd.rs, src/mp4box/trun.rs, src/reader.rs, src/track.rs, src/writer.rs
Initial effort to reduce or eliminate the use of assertions in the production code (see issue 55). I'm certain these changes will need refinement, this is just a first pass. Not all of the changes were as simple as returning an `Err`, since some functions did not return a `Result`. Also, the error type used (`InvalidData`) is just a catch-all with a message, and in some cases a more refined error type may be in order.
=> Attempt to minimize assertions in non-test code

Cargo.toml
Ensuring that projects that depend on this crate don't include old or potentially semver-incompatible versions of crates.
bytes 0.5 -> 1.1.0
num-rational 0.3 -> 0.4.0
I ran `cargo test` and everything still passed. 
Is there a plan to release a `version = "0.9.1"` patch version of this crate (if no breaking changes were made since the last release) in the near future?
=> upgrade dependencies

src/reader.rs
=> bugfix: break reader loop if BoxHeader is size zero to prevent dead-loop

src/lib.rs
Instead of only exposing Mp4Box type, expose all box types to consumers.
=> expose all box types

examples/mp4info.rs
(plus running it through cargo fmt)
For instance checking https://download.blender.org/demo/movies/BBB/bbb_sunflower_1080p_60fps_normal.mp4
It will show all the tracks:
```bash
$ cargo run --example mp4info  ~/bbb_sunflower_1080p_60fps_normal.mp4
File:
file size:          355856562
major_brand:        isom
compatible_brands:  isom avc1 
Movie:
version:        0
creation time:  1387216772
duration:       634.533s
fragments:      false
timescale:      600
Found 3 Tracks
Track: #1(und) Video: h264 (High) (avc1 / 0x61766331), 1920x1080, 4004 kb/s, 60.00 fps
Track: #3(und) Audio: mp4a box not found
Track: #2(und) Audio: aac (-) (mp4a / 0x6D703461), 96000 Hz, -, 160 kb/s
```
=> Do not fail if media info fails

src/mp4box/stco.rs, src/track.rs
This change allows Mp4Writer to support writing mp4 files that are larger than 4GB. Previously the Chunk Offset Atom was used exclusively, so if you built an MP4 file that was larger than 4GB, the Chunk Offset Atom was silently corrupted. This change uses the co64 atom by default, and then checks for stco compatibility at the end of the track write. If all the offsets are under the 2^32 limit, then a stco atom is written, otherwise a co60 atom is written.
=> Mp4Writer should use co64 by default, then convert to stco is possible for compatibility

src/track.rs, src/writer.rs
Currently the version of the `mvhd`, `tkhd`, and `mdhd` boxes default to 0 in the mp4 writer. This can be an issue if the duration of a track, as defined by the timescale, exceeds u32::MAX. If u32::MAX is exceeded, the duration will end up corrupted as the upper bytes are just truncated. 
Alternatively, maybe the library should fail writing boxes when fields would overflow?
=> Set mvhd/tkhd/mdhd version to 1 if duration is greater than u32::MAX

.github/workflows/rust.yml, examples/mp4dump.rs, src/mp4box/avc1.rs, src/mp4box/dinf.rs, src/mp4box/edts.rs, src/mp4box/hdlr.rs, src/mp4box/mehd.rs, src/mp4box/mod.rs, src/mp4box/mp4a.rs, src/mp4box/tfhd.rs, src/track.rs, src/types.rs, tests/lib.rs
This PR fixes clippy errors and enhance the CI/CD with clippy checks and running latest rust version.
I would recommend to have a deep look at commit `fix clippy::unused_io_amount` : it allowed to fix a bug in `mp4a` parsing, where `BoxHeader::read` errors were silently ignored and could lead to "overflow read". But now the change could make `mp4` returns an error in some cases where it did not and could break existing code based on this bad behavior.
Up to you to release it as a breaking change release or not. 
Last I would recommend to check whether my fix for `fix clippy error with always 0 value` is correct. There was truly a bug, but I am not completely sure my fix is the one expected.
Cheers.
=> fix clippy & enhance CI/CD

src/mp4box/mod.rs
The subtraction overflow will cause a panic when overflow panics are enabled. It seems more robust to return an error instead. The 64-bit box size can only be this small in malformed files, but I'm working on a project to parse and sanitize untrusted MP4 using this library, and hopefully panics can be reserved for code bugs rather than malformed input.
=> Don't subtract overflow when 64-bit box size is less than 8

src/mp4box/data.rs, src/mp4box/ilst.rs, src/mp4box/meta.rs, src/mp4box/moov.rs, src/mp4box/trak.rs, src/mp4box/udta.rs, src/reader.rs
The meta box is very open-ended, leaving itself open to extension by future specs. This PR:
1) parses the `Hdlrbox` as required by the spec for the meta box
2) only parses iTunes metadata when the handler type is `mdir` (as seen in `big_buck_bunny_metadata.m4v)
3) makes `MetaBox` into an enum, to allow for other handlers in the future (like requested in #66)
4) allows parsing `MetaBox` in more positions as per the spec
5) writes metadata out if present
=> Parse unknown metadata and write metadata

src/mp4box/avc1.rs, src/mp4box/co64.rs, src/mp4box/ctts.rs, src/mp4box/dinf.rs, src/mp4box/edts.rs, src/mp4box/elst.rs, src/mp4box/ftyp.rs, src/mp4box/hdlr.rs, src/mp4box/hev1.rs, src/mp4box/ilst.rs, src/mp4box/mdia.rs, src/mp4box/minf.rs, src/mp4box/moof.rs, src/mp4box/moov.rs, src/mp4box/mp4a.rs, src/mp4box/mvex.rs, src/mp4box/stbl.rs, src/mp4box/stco.rs, src/mp4box/stsc.rs, src/mp4box/stsd.rs, src/mp4box/stss.rs, src/mp4box/stsz.rs, src/mp4box/stts.rs, src/mp4box/traf.rs, src/mp4box/trak.rs, src/mp4box/trun.rs, src/mp4box/udta.rs, src/mp4box/vp09.rs, src/reader.rs, src/track.rs
Add checked arithmetic in several places where the code:
* Reads a length from an open file, and tries to allocate that much memory
* Subtracts from a length, overflows if it's unexpectedly small, and tries to allocate that much memory
* Performs unchecked arithmetic on a value (e.g. to compute a sample_id), and panics (in debug mode)
(da83d3c isn't an overflow per se, but I think it's in the same spirit.)
=> Fix several overflows in box and track processing

src/lib.rs
=> Fix link to examples in docs

src/types.rs
Noticed that the CI was failing because of this in #99
=> Derive Default trait for DataType

src/mp4box/meta.rs
The spec seems to allow the hdlr box to be located at any place in the meta box. This commit addresses that.
=> Allow Hdlr to be not the first in the Meta box

src/mp4box/meta.rs
Fixes #102
---
I've made sure `cargo test` still works, but I haven't looked into the tests to see if they actually cover this piece of code. So if they don't, more testing is needed.
Other than that, I've tested this with my mp4 files that were affected by #102 and it fixes the issue for me.
=> Try to skip extended header in MetaBox.
